all : bc ws cl labindex

bc : bc_zero bc_one bc_two bc_three bc_four bc_five bc_final labindex

ws : ws_one ws_two ws_three ws_four ws_five labindex

cl : cl_1 cl_aws cl_gcp cl_hwk

mw : mw_one

.PHONY : all

labindex : FORCE
	./buildindex.sh

mw_one : FORCE
	# BSidesPDX 2018
	# claat export 1rOYr4YyIUhvpzCPzKqKViEesNCD9yve5KuzvKJClFzc
	# VM setup
	claat export 1SxgVmbBX3_Fsj8_9KpVV5bU7NZmmpBFrwbY5cF3xyQQ
	# AFL
	claat export 1nMJH1COPXHdLxkF1tvVHdu-9I6q7kpom9rcLm7exkkw
	# angr
	claat export 1B6vgQlp6AFsW8C4TGdxVLAmmL1UrZIwHMx8vs0OFvhs
	# final projects
	claat export 1BsU5XE73_TOg5UBvXKVHF9Hi7HyPLI7GM1q56HXxPro
cl_1 : FORCE
	# HW1/Setup
	claat export 1SCxbhUZNE7jlOXNkzTOaoI4GoAQxtIiBgH7PfM00Az8
	# arp, wireshark, netsim
	claat export 1xziM5JoSWO2CG0b1X1t8_dhjYWdccZ0PDtZqsHQAaOo
	# nmap, GCP networking
	claat export 1AdwlM9CNRhHtKBb6hjue6u-gR4hfTA3cTkanMuWwT-I
cl_2 : FORCE
	# TCP/HTTP (netstat, lsof, nc, iperf, browser tools)
	claat export 1aGOg-1bK_fazW3Tl1tb9E8apLnya5-FfflGqVQbYyvw
	# DNS/Recap (dig, wireshark)
	claat export 1g1eFzkRHpqlQnU_wcIV48uasKWX8DvouOOOkdTjE79o
cl_3 : FORCE
	# python/flask guestbook
	claat export 1hSEOKiJGAd-okfgWFGupgrQb4eRt4PmjUXPFxcy1tPY
	# SQL RDS+CloudSQL
	claat export 1MYLBTJzxaJwV_PlheOH7eifEECrHIKetDK8mGOPfLW8
	# sqlite3 guestbook
	claat export 14Z_gNlWewTGRPsR31hiT1qF84w8TdY1tszO-i8y6hzo
	# HW2
	claat export 1vQa9JE5S_awVIE4whRfJJOyRzc97kH2Mr7YBRwr9Hfg
cl_4 : FORCE
	# nginx EC2 guestbook
	claat export 1e8aHY79zf65m3v-v_syy6ZUpYsHd4bl8rFnZ9ljrJls
	# nginx computeengine guestbook
	claat export 1lwIl9XdpezC75WnmJV5wKKIu35O4_OGe_80cfPs0564
	# docker guestbook
	claat export 1zaZFew4_D9aRvfflHyYt2Nv6h5ADMc9wwPQ8B7ODVp4
	# HW3
	claat export 1W06McP4v73S3vAAfSZyFFpONCY7bzo6z06qnCSyoH38
cl_5 : FORCE
	# datastore guestbook
	claat export 1N_pFWnIUN4s1gQbCqeCoKCkPkJEuI1FwlgqAB0ORe0o
	# storage, iam
	claat export 1yaH-YHwD9TwNsR_8RR-dkH8_r_mEVZhjVTfoADdSbrA
	# DynamoDB guestbook
	claat export 12TEEFFhW6ghz5pb24vqXgQumPr52vvjTGg95nZqJEno
cl_6 : FORCE
	# appengine guestbook
	claat export 19l3Xgmqk9HWW5vprRCGxC3zq1Jly6x0n_TDIlL0FEMI
	# cloudrun guestbook
	claat export 1Uy-f2K5NfNE5B_f6BBcgaRfbOfb_UBQe5JtYbM7oZtc
	# cloud run web proxy
	claat export 1MnWgHWHpm8gDvLthznKSQmLi90KdjZSzWu3ytho3P6M
	# ECS guestbook
	claat export 1noYCMycw6F-sI0aRDPPl0moO743Y2-m9mKozTuMAG6w
	# EB guestbook
	claat export 1IERezDGuYyVIekbkglqZan_HQ93ZdnwQyC1iDr3QyuE
	# cloud function (image blurring)
	claat export 1QyFX6Xxw7U15ZzeHiMKEey_l4oUjdyvM_fhgW6aYttQ
	# lambda MOTD
	claat export 1TMczDRPgisMXf3IJw0tWUbGjoR7dW7Cgu8Cx8_NPPSM
	# HW4
	claat export 1w5ahQ4KJegSR2Af2OGmc5gYHdNQtFIV76hSMLHmmHfE
cl_7 : FORCE
	# kubernetes guestbook
	claat export 1Sb23-zsHTHYAsaC6T364lmL-0VzDkF6pXj6ceNfx04k
	# cloud functions guestbook
	claat export 1h5DdQrs6Mwxys4BuVFeonpY_AJLsQoThCjF1IaC_7Tw
	# lambda getTime api gateway
	claat export 1FS8wBTEdp0K2Bs_A13LQiJeTLCisO6hJTCmHdOmyTmw
	# api (slack+knowledge graph)
	claat export 1t9S3A60L3G4o0KqRllZHnHyGdLfuvtbAvQAQKrt0W_E
	# lambda guestbook
	claat export 1G67OUhA7kSMh_OjvlI4GvkjowC1zvT4sT-re_iCqi08
cl_8 : FORCE
	# cloud functions guestbook deployment manager version
	claat export 1YPFbqOAbmft9a5QPoVk0xMu4dMbQLMJiTMKa2jMcXO0
	# ml apis
	claat export 1PBmtYGIRYcQShxRrtjrZ9GxlMuaFyhQ5ToZr3omuPFw
	# firebase
	claat export 1nYBBYzVHmHarWTx4Yt1CHk72YfYP3sUCINEgXKoW7eY
	# lambda guestbook CDK version
	claat export 16eHpMMWmfWVTHnqhlTpikQkUeasYEMfoy7NusoGjBTw
cl_9 : FORCE
	# Final
	claat export 1KiHxAdqKO7D4Gr1Y8HmmkgTD1o0gHIR4QNNPK6djF5Y
	# bq, notebooks
	claat export 1R2fSw-KZ_QXzn5Q5l5jtCk-W_x_sJ0hbexhTpt-iwNw
cl_10: FORCE
	# deployment manager cdn
	claat export 1eVUzpLXVADDSgQHyjPvnCsmSKGoHbWlSVMFrFdeAQx8
	# dataproc, dataflow
	claat export 1unbUdzzN0CDYoK96gx2YueL6QYCjqyxDK9qRnas7-Kk

bc_zero : FORCE
	# 0 setup
	claat export 1NXiogMwVHp-jOIeXLu2Q7H7yC-BYXCAipOu9u5fpRCo

bc_one: FORCE
	# 0 sawtooth
	# sawtooth01 (Mine)
	claat export 1t0UIfyzonvbbKIpKa1zx1ycipfOjwoFsYn2IZdTSRKk
	# sawtooth02 (Mine)
	claat export 1CrrDaMApSTqbDaRjmFkuMr7POUzQFYpDQrkh3zdK950
	# sawtooth03 (Mine)
	claat export 1O4YyH06hjacaedy751Eav4-GGE8AMMcmLcgC9jwd6CQ
	# sawtooth04 (Mine)
	claat export 1hM0BiMmsuOXozQ6_j3Sbtvjzkdol3TkU5ThicKZZhVE

bc_two: FORCE
	# 2 solidity
	# s1_metamask_sictf
	claat export 1Sb-WScQ4IfUy1xQtEDQh38Js_1N4yI_YpAJOmmd5Ej8
	# s2_solidity_cryptozombies
	claat export 1dy4faWXdIrDK03quK6kpPxWBbmjJpUXen0fEVASPCow
	# s3_remix
	claat export 1i3YgtEoM61iixwHhse3qzk56rW8qi6_mmAPp6tY2wsE
	# s4_smartcontracts
	claat export 1vCYJSBDd8CtCtZp2PLlDYvC235chC1CSvk8_eaRRTY0

bc_three: FORCE
	# 3 sictf
	# sictf_donation_lockbox
	claat export 1TC1VRT65rSXRcTXgfca6AHtZFHI7N3ctN4gto6U9mRc
	# sictf_headsortails_lottery
	claat export 1zNRvbdPje6OGqucEUTWklhqSe39zPiGD9Nxha47L8fc
	# sictf_tokensale
	claat export 1jodKRYTCl5kdHZojNTsf3JbnL8dhVEUtMUlTyltCTuM
	# sictf_piggybank_securebank
	claat export 1PRwVOhzbl-UwxgFfL-yiRtcvHOfOfLnEUoPddxM24iY
	# sictf_recordlabel
	claat export 16NMZXmJf-nmnLeZVhhvkK_QM5x34hIVWiaDb70VyAMo
	# sictf_trustfund
	claat export 1lqJmimBtSkFToNngZEZreD3jZhABcszz-Pr_oQJm7ig
	# sictf_slotmachine_rainydayfund
	claat export 1XliBHA31PQkR-I5Z4LxI1HFI9dTTmX1uC9J4egLCsfA
	# sictf_raffle
	claat export 1NbnAWijP-xzyKcp-G6yyl1aTcMuez3NZjRqqJB_htHQ
	# sictf_scratchcard
	claat export 1M531Cub4P_8UTOyYC6Jd1aBiewePYXOlSX6WaB29I8A

bc_four: FORCE
	# 4 vyper
	# vyper_intro
	claat export 1BikDdjpVDjyRokWXNxJiTIfK9LqODhRerJWeVwYuytk
	# vyper_fundraiser
	claat export 1IISJwrxBJm8kbcPSGL03rJEUO5xGJzhxcTU-S5yfYQo
	# vyper_guestbook
	claat export 1IhbP9gwPbA3HwslIFx7nLStAwDFDfuOLdCVp8cq2pzo

bc_five: FORCE
	# 5 manticore
	# 5.1 setup
	claat export 1ZzbFk-Yo1dlwVeulNDZSzYoJJC-eWkRLj7E_Ji00_yo
	# 5.2 donation
	claat export 1L8Vihw1hGYQdA3sb1TtQGyEEj54m_JzeHth1cgO6UH4
	# 5.3 piggybank
	claat export 1iTsHx2fqnqx188Kv2ClTRJTCoxslW5eS8aez2k9RPXA
	# 5.4 lockbox
	claat export 1urL3iJieRW-mDx9kXrBD22NlQTYbtAzzFZkDeh2W6YY
	# 5.5 lottery
	claat export 1bnk73XqHxd0oc5KRjB2xc4jHVxWmozAtKlglNcR4lRA
	# 5.6 trustfund
	claat export 1UAqacMP073mR-pSfmXOJYo2ZwXAYMeOqMHSXHeIqDAo

bc_final: FORCE
	# 6 final
	claat export 1mAB9acIORNWN5XAc8pwKCFCPJNqOGV_wC00F5mkFyf4

ws_one:
	# Setup
	#claat export -pass_metadata tags ?
	claat export 1wa_KHELOieWE9-8ls_Vsg4Za4boH4Xydp7VOX_uWC0w
	# 1.2 Web programming
	claat export 1hg2QWIIbwvWLyMx33BKp4JpNjzJWcarXKGZW3RMbb_g
	# 1.3 Authentication
	claat export 18_EdajNo5VJZb-Veg7CzVDCCiLA4Q8amzEzRF_Wg4J4
	# 1.4 HW1 2fa-bypass-using-a-brute-force-attack
	claat export 17FL7FOT6naN1I-u4Cvo6A88sZSpsZ9P2gqS0OxojSR0
	# 1.4 HW1 2fa-broken-logic
	#   claat export 1uQIeFcj_Ojx91tu8o97pUhmKmdnOkbBosftNfVjaDCk
	# 1.4 HW1 Timing Side-Channel (wfp2)
	#   claat export 1CoOun-25m29tIZI-WfHWcAacg6bCGYyxpVCMZlE2BsU
	# 1.4 HW1 username-enumeration-via-response-timing
	#   claat export 102DSJHMOrP0r5mk0pWQoLaRtEnozEfPaVZBIcGkrQdI
	# 1.5 Access Control (file-path-traversal, access-control,
	#     information-disclosure, wfp1-fileupload)
	claat export 1fcgAGPnZ7fGWsmzkmCdx5LP16Rw7GukcNAWEfb1SdtM
	# 1.6 SSRF
	claat export 1P7Wk1OjnGx-0M-ranrdkR2mx8T2ONgr4-3z4WoN-oMY
	# 1.7 XXE
	claat export 1a35r84x6_BmQHNevwKmnUBj3CjDZCXpYufk1Udnumc8

ws_two:
	# 2.1 Command and SQL Injection
	claat export 1kZtOhMjqnfVyNJK-rhJPxbJpZlX-C7uGa1mbwvwmIks
	# Old Injection-SQLi (WFP)
	#   claat export 17mjW0pY7sKJElAkTz-zpt5WLktqm5XfAJuVqCKmU4eo
	# 2.2 HW2 WFP2 MongoDB Blind SQL Injection
	#   claat export 1WblWTNPLNRHOz5nxTKFiJ8Dpc8u0e-MEbj7_9v-3JUU
	# 2.2 HW2 conditional-responses
	claat export 1YE5pFki1XsbEktNpVbHKMN9odgJW7xcvLjX0CHwh-mA

ws_three:
	# Old XSS (WFP, XSS-game)
	# claat export 1kjNMJkHUb4ZU4dbReppFVB_WY0WOHfzJjG1doxMS0gk
	# XSS (PS)
	claat export 1AlqyaRjGCdmczJvJe1zgYdwlV7DhupDndUz4Y_P5yIE
	# CSP/CORS (NodeJS, PS)
	claat export 1G6FDoaQkasvJavHgXG8BwQGgB5P_YwL6QX_Vu5Bi8cI
	# CSRF
	claat export 1NrOCVOReEndKihcFZNyHKWgKpvIOZYefi5AaDK3SCD4
	# Clickjacking
	claat export 1z15wws-cTrL_H3JTZdYpACK-s4tij-pfO7tKJyH6Y3w
	# Deserialization a8 (JavaScript)
	claat export 1U0TQUivuECCd4t8NlrO6Q3ULKN8EYRdHUuuiRLW3LuI
	# Deserialization a8 (PHP)
	claat export 1TdiiQK4Ka6WFiQp_w89EmL3fdJFgFJfAJr3pYU3U2wI
	# IanD/Grace Portswigger Levels
	# claat export 1E93xNRalFk7urRbzfUh19IuMY5k98MGYgdaqAVvSuRs

ws_four:
	# 1: Thunder CTF
	claat export 1axp_jL9bg5t5Nwsn6WVR8NOalZ1hbqMZ_OFmb1LEgXY
	# 2: AWS Serverless Goat
	claat export 1oRssROE86iWS-HjK8XnDcYt1wgW2Je8N7atoyTu8fDo
	# 3: AWS Flaws
	claat export 1uGiIjgIH6ZvUVmuBdlBMAHz3g6KS0PN_UpWMLtu3_78
	# 4: AWS Flaws2
	claat export 1joRqUHIdKA7dtjUdTUnD1fpM5inT1XzJJdMJg54rNbI
	# 5: AWS Cloud Goat
	claat export 1-4Lyk8f_hWbEYBqLYazIYeqVpQ-uUE698rVjJVGCc3s

ws_five:
	# Tools t3 (old?)
	#claat export 1fCboO_ebRoes6-IH91FEry3EUYYZ9UFiiZTsGqN_w4M
	# 5.1 (setup)
	claat export 1FTiXmWmlKmb1-gasIBHTi7Zk8S-cJPbKdoyj4seOhMg
	# 5.2 (wfuzz, nmap, bucket-stream)
	claat export 1o6cAJ8RAa-ynLpeP6xPsZ5NSF9RYgSr-3-PSY-3gZGs
	# 5.3 (wpscan)
	claat export 1xlRiQvumhVU5Qzr_zjIRXojwxH46xhYZ1lXtlTaY50w
	# 5.4 (hydra, sqlmap, xsstrike, w3af, commix)
	claat export 16XyONjg3yGjqRDxAJoYPo5I3lOgANTHvz6gzRDxcJpo
	# 5.5 (metasploit)
	claat export 1sDUBNQC5gSosULqLvv-IZrkmwfA7UUmO4Otmmi3lBwA

update: FORCE
	claat update

clean: FORCE
	rm -r [1-5].*

FORCE:
